name: key_value_store_web
description: A multiplatform key-value store implementation for web.
version: 1.0.0
homepage: https://github.com/roughike/multiplatform_key_value_store
author: Iiro Krankka <iiro.krankka@gmail.com>

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  key_value_store:
    git:
      url: https://github.com/dclcs/multiplatform_key_value_store.git
      path: key_value_store

dev_dependencies:
  build_runner: ^2.4.8
  build_test: ^2.2.2
  build_web_compilers: ^4.0.9
  test: ^1.25.2
  mockito: ^5.4.4
