name: key_value_store_flutter
description: A multiplatform key-value store implementation for Flutter.
version: 1.0.0
author: Iiro Krankka <iiro.krankka@gmail.com>
homepage: https://github.com/roughike/multiplatform_key_value_store

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  key_value_store:
    path: ../key_value_store
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  plugin:
    androidPackage: com.roughike.keyvaluestoreflutter
    pluginClass: KeyValueStoreFlutterPlugin